### PR TITLE
Fixed Projectile Collision Bug

### LINKED ISSUE #428: BUG: Game Crashing When Projectile Hits Tree!
## Description
The game crashes if a banana (from a monkey throw) comes into contact with a tree. This is because the target (the tree) has no combat stats component and so a null pointer is returned when attempting to get it as this is not accounted for. Dereferencing this null pointer leads to the game crashing.

## How To Reproduce
1. Go to the entitySpawn.json config file
2. Set all values to 0.
3. Set NUM_MONKEYS to 20 (or some other similarly high value)
4. Set NUM_TREES to 30 (or some similarly high value)
5. Play the game, and try to get monkeys to throw bananas at you. 
6. Attempt to move in such a way that the projectile will hit a tree that is between you and the monkey.
7. Observe the game crashing:(

## Expected Behaviour
The game should not crash, in fact the projectiles should have no influence on any non-player object (ie hitting another monkey should not incur friendly fire - if this isn't what we want this is a design decision that can be made later).

## Screenshots
Screenshot 2024-09-29 at 12 57 52 PM
Screenshot 2024-09-29 at 12 58 02 PM

### PR DESCRIPTION
**Pull request by mitsudz**
# Description
This changes fixes the bug #428 where if a projectile (banana from a monkey) hits a tree the game crashes. I have added a flag to determine whether an entity is a player - and upon player creation this is set (defaults to false). Then, projectiles will only damage the player (ie friendly fire between monkeys or other enemies cannot happen - if we want this to change it can be determined by the design comittee).

Fixes / Closes #428 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?
Complete the testing protocol described in #428 to reproduce the bug, and observe that in main (before this pr) the game crashes, and afterwards it doesn't.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by PHONGNGYUEN1 — APPROVED** [review]

File: source/core/src/main/com/csse3200/game/entities/Entity.java [hunk 1]
```diff
@@ -64,9 +68,8 @@ public EnemyType getEnemyType() {
   }
 
   // Setter for enemy type
-  public Entity setEnemyType(EnemyType enemyType) {
+  public void setEnemyType(EnemyType enemyType) {
```
Comment (jakingy) [inline source/core/src/main/com/csse3200/game/entities/Entity.java:71]: I believe the purpose of returning entity here was to allow for chaining e.g. 
```java
new Entity()
                        .addComponent(new TextureRenderComponent(imagePath))
                        .addComponent(new CameraZoomComponent())
                        .addComponent(new PhysicsComponent(true))
                        .setEnemyType(enemyType);
```

File: source/core/src/main/com/csse3200/game/entities/Entity.java [hunk 2]
```diff
@@ -48,14 +49,17 @@ public enum EnemyType {
...
   public Entity() {
-
     id = nextId;
     nextId++;
 
     components = new IntMap<>(4);
     eventHandler = new EventHandler();
   }
 
+  public void setIsPlayer(boolean status) {this.isPlayer = status;}
```
Comment (jakingy) [inline source/core/src/main/com/csse3200/game/entities/Entity.java:59]: Maybe we should have an EntityType that includes EnemyType, Player, Friendly NPC type etc

**Review by jakingy — APPROVED** [review]
Tested in-game and verified bug is fixed, but it might be good to refactor EnemyType and isPlayer into a single EntityType enum.

**Review by Howard-12 — APPROVED** [review]

File: source/core/src/main/com/csse3200/game/entities/Entity.java (hunk 1 above)
Comment (mitsudz) [reply source/core/src/main/com/csse3200/game/entities/Entity.java:71]: Fixed

File: source/core/src/main/com/csse3200/game/entities/Entity.java (hunk 2 above)
Comment (mitsudz) [reply source/core/src/main/com/csse3200/game/entities/Entity.java:59]: We could, but currently every single enemy has it's own enum value - that should be refactored first. For now I don't think that's relevant to this pr although that should be refactored later.
