### PR TITLE
4/dialogue box bugs

### LINKED ISSUE #336: [Team 4] DialogueBox Bug Fixes
# **Description**
**Task:** DialogueBox Bug Fixes.
**Feature:** [Team 4] Friendly NPC Interaction Update and Extensions #326

This task ticket entails fixing some bugs identified by the studio including issues with game ticks and displaying the game, resizing of the dialogue box, and other issues that peers may present. 

# **Dependencies**
There are no dependencies as these are bug fixes. 
 
# **Milestones**
List of steps that need to be completed for this task.
- [x] Fix issue surrounding dialogue box disappearing & not returning on a specific tick (Sep 14)
- [x] Fix resizing (Sep 14)
- [x] Document testing for resizing (Sep 14)
- [ ] Added key bindings for left and right arrow for the Dialogue Box (Sep 14)
- [ ] Testing for ket bindings regarding the above (Sep 14)
 
**Completion Deadline:** September. 20
 
# **Documentation**
- [DialogueBoxTesting](../wiki/Dialogue-Box-Service-Testing)
 
# **Member**
- e.g. Bailey (@BaileyS03) (Bailey Stoodley)

### PR DESCRIPTION
**Pull request by BaileyS03**
Fixes some requested issues presented in class that were causing some bugs with the Dialogue Box. 

See testing for some documentation
https://github.com/UQcsse3200/2024-studio-2/wiki/Dialogue-Box-Service-Testing

Closes #336

### CODE REVIEW

File: source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java [hunk 1]
```diff
@@ -92,6 +96,11 @@ public void update() {
             // NPC pauses when close enough to the target
             hasApproached = true;
             movementTask.stop();
+            logger.info("Pausing");
```
Comment (mitsudz) [inline source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java:99]: Can we set this to debug - there'll be a lot of these popping up if anyone wants to do functional testing.

File: source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java [hunk 2]
```diff
@@ -1,14 +1,18 @@
 package com.csse3200.game.components.tasks;
 
+import com.badlogic.gdx.utils.Logger;
 import com.csse3200.game.entities.Entity;
 import com.csse3200.game.components.ConfigComponent;
 import com.csse3200.game.entities.configs.*;
+import com.csse3200.game.services.ServiceLocator;
 
 /**
```
Comment (mitsudz) [inline source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java:9]: Not specific to this PR, but might be good for overall modularity to have this task inherit from ProximityTask and override certain functions. Haven't looked into too much detail so not sure how viable this is though.

**Review by mitsudz — APPROVED** [review]
Looks good - 1 change requested and 1 comment written.

**Comment by EllaBerglas** [comment]
There seems to be issues with resizing dialogue text and play button location

File: source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java [hunk 3]
```diff
@@ -132,79 +170,71 @@ private Label createLabel() {
...
         TextButton.TextButtonStyle buttonStyle = createButtonStyle();
-        TextButton playButton = new TextButton("Play Game", buttonStyle);
+        playButton = new TextButton("Play Game", buttonStyle);
         playButton.getLabel().setAlignment(Align.center);
         float buttonWidth = playButton.getWidth();
         float buttonHeight = playButton.getHeight();
         float centerX = (screenWidth - buttonWidth) / 2;
         float centerY = (screenHeight - buttonHeight) / 2;
 
         playButton.setPosition(centerX, centerY - 300);
```
Comment (EllaBerglas) [inline source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java:232]: This my fault with the -300 (I'll make sure to fix that). But the screenWidth and screenHeight don't seem to update when the screen resizes.

File: source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java [hunk 4]
```diff
@@ -101,29 +106,62 @@ public DialogueBox(String[][] labelText) {
...
+        float newWidth = screenWidth;  // Full screen width
+
+        backgroundImage.setSize(newWidth * 0.9f, desiredHeight);
+        backgroundImage.setPosition(newWidth * 0.05f, screenHeight * 0.09f);
+    }
+
+    /**
+     * Resizes the background image for formatting
+     */
+    public void resizeElements() {
```
Comment (EllaBerglas) [inline source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java:123]: should also resize text in the dialogue box

File: source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java [hunk 5]
```diff
@@ -358,6 +396,66 @@ public void handleBackwardButtonClick() {
         updateLabelPosition();
     }
 
+    /**
+     * Resizes and spaces the buttons based on the number of currently visible options.
+     */
+    public void resizeOptionButtons() {
```
Comment (EllaBerglas) [inline source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java:402]: resize play button as well?

**Review by EllaBerglas — CHANGES_REQUESTED** [review]

File: source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java (hunk 1 above)
Comment (BaileyS03) [reply source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java:99]: This is just being removed - I forgot about it sorry!

File: source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java (hunk 2 above)
Comment (BaileyS03) [reply source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java:9]: Hi, it inherits from chase task which has a lot of the same metrics and calculations. ChaseTask inherits from this. Do you still want this overridden?

File: source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java (hunk 4 above)
Comment (BaileyS03) [reply source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java:123]: It does on line 139 - Did you have issues with this?

File: source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java (hunk 5 above)
Comment (BaileyS03) [reply source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java:402]: Sure.

Comment (BaileyS03) [reply source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java:408]: This is now done please check you are happy with the new implementation. Regarding this since our team was not responsible for this do you expect us to develop tests?

File: source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java (hunk 3 above)
Comment (BaileyS03) [reply source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java]: Now dynamic.

File: source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java (hunk 5 above)
Comment (EllaBerglas) [reply source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java:408]: Nah I can do that, the play button doesn't still quite resize properly like the continue and back but I can have a look at that.

File: source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java (hunk 4 above)
Comment (EllaBerglas) [reply source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java:123]: Yeah, the actual font in the dialogue box (or buttons) dont resize

File: source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java [hunk 6]
```diff
@@ -93,6 +97,10 @@ public void update() {
             hasApproached = true;
             movementTask.stop();
         }
+
+        if (hasApproached == true && Boolean.FALSE.equals(ServiceLocator.getDialogueBoxService().getIsVisible())) {
```
[the remark this answers is not in the document]
Comment (BaileyS03) [reply source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java:101]: The SonarLinter told me to do so, so I did. I originally used this but I was hoping to make sonar cloud happy. Do you still want me to change this?

File: source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java (hunk 4 above)
Comment (BaileyS03) [reply source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java:123]: Yep, heard loud and clear. I'll work on this now.

File: source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java (hunk 5 above)
Comment (BaileyS03) [reply source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java:408]: I know exactly why. Can you provide the SetSize code you would like? I can do it the exact same but I was not asked to do this hence just fixed your positioning.

File: source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java (hunk 6 above)
[the remark this answers is not in the document]
Comment (LucasRyall) [reply source/core/src/main/com/csse3200/game/components/tasks/PauseTask.java:101]: fair point, while I personally don't like it its probably better to stay consistent with sonarlint, so keep it as is.

File: source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java [hunk 7]
```diff
@@ -132,79 +176,71 @@ private Label createLabel() {
...
     /**
      * Creates the forward button for navigating to the next hint.
-     *
-     * @return The TextButton instance.
      */
-    private TextButton createForwardButton() {
-        TextButton.TextButtonStyle buttonStyle = createButtonStyle();
-        TextButton forwardButton = new TextButton("Continue", buttonStyle);
-        forwardButton.getLabel().setAlignment(Align.center);
+    private void createForwardButton() {
```
[the remark this answers is not in the document]
Comment (BaileyS03) [reply source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java:199]: I believe I have fixed this, would you mind taking another look please?

File: source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java [hunk 8]
```diff
@@ -132,79 +176,71 @@ private Label createLabel() {
...
      * @return The TextButton instance.
      */
-    private TextButton createBackwardButton() {
-        TextButton.TextButtonStyle buttonStyle = createButtonStyle();
-        TextButton backwardButton = new TextButton("Back", buttonStyle);
-        backwardButton.getLabel().setAlignment(Align.center);
-
-        float buttonWidth = backwardButton.getWidth();
-        float centerX = (screenWidth - (2 * buttonWidth + 35)) / 2; // 35 is spacing between buttons
+    private void createBackwardButton() {
```
[the remark this answers is not in the document]
Comment (BaileyS03) [reply source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java:216]: The back button is always functional for me but doesn't make sense as times hence this is how I interpreted this. I just pushed a change for this to make it more intuitive.

File: source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (LucasRyall) [reply source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java:199]: looks good, very occasionally (i cant replicate it just happens sometimes) when you hit continue it restarts the dialogue. I think its because of walking into them again while the dialogue is still up, but I'm not 100% sure. not sure if this was intended but your change also lets you get rid of the dialogue box for items which is nice.

File: source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java [hunk 9]
```diff
@@ -101,29 +106,68 @@ public DialogueBox(String[][] labelText) {
...
+        float newWidth = screenWidth;  // Full screen width
+
+        backgroundImage.setSize(newWidth * 0.9f, desiredHeight);
+        backgroundImage.setPosition(newWidth * 0.05f, screenHeight * 0.09f);
+    }
+
+    /**
+     * Resizes the background image for formatting
+     */
+    public void resizeElements() {
```
[the remark this answers is not in the document]
Comment (LucasRyall) [reply source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java:127]: Recent changes seem to have fixed this crash.

File: source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java (hunk 7 above)
[the remark this answers is not in the document]
Comment (BaileyS03) [reply source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java:199]: I know why its happened but I am unsure of who is causing it. It am imagining the bananas hitting our entity is triggering some event. This is something I did notice myself but I need to figure out who is triggering some event on the FNPC. 

If you wanted to know, in PauseEvent it relies on the last event being called is the PauseStart[AnimalName]. If this wasn't the last event called on the FNPC it will open the dialogue again from the start.

**Review by LucasRyall — APPROVED** [review]

File: source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java (hunk 5 above)
Comment (EllaBerglas) [reply source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java:421]: Yeah I understand just thought while you were at it to make it the same as the others if it's easy. I'll approve without this tho and I'll fix it later if it's a bother (just don't feel like doing this course rn).

File: source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java (hunk 9 above)
[the remark this answers is not in the document]
Comment (BaileyS03) [reply source/core/src/main/com/csse3200/game/ui/DialogueBox/DialogueBox.java:127]: I took the setScaleFont out, I will need to create new fonts and scale it that way which is a much more time consuming task.

**Review by EllaBerglas — APPROVED** [review]
Seems good now
