### PR TITLE
3/speed up inventory

### LINKED ISSUE #524: Game Crashing On Eating Multiple Milk
## Description
Consuming multiple milk's crashes the game

## How To Reproduce
1. Open game
2. Find a cow and communicate with it enough times to spawn 2 milk (from the same cow)
3. Pick up both milk
4. Consume one milk followed by the other -> the game will crash

## Expected Behaviour
No crash

### LINKED ISSUE #525: Inventory Lags When Full
## Description
As the inventory becomes more and more full the game lags more and more.

## How To Reproduce
1. Start a new game
2. Move around and pick up many items
3. View the game begin to lag as new items are picked up when the inventory becomes more full.

## Expected Behaviour
No lag regardless of how many items are in the inventory.

### PR DESCRIPTION
**Pull request by mitsudz**
# Description
This PR does 3 things:

Delete redundant Inventory backend code which is not being used.
Fixes bug where when you pick up multiple milk from the same cow and consume more than one.
Fixes lag in game when interacting with inventory as it becomes more full.

Closes #524 
Closes #525 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Current unit tests still pass and have been updated to be compatible with the new inventory backend.
For the bug fixes, try going through the steps written in the issue before and after this pr (ie the current state of main and this branch). The bug is present on main but not on this branch.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

File: source/core/src/main/com/csse3200/game/inventory/Inventory.java [hunk 1]
```diff
@@ -442,7 +338,14 @@ private Optional<Integer> getItemIndex(int code) {
...
     private Optional<Integer> getItemIndex(String name) {
-        return this.hasItem(name) ? Optional.of(nameToIndices.get(name).first()) : Optional.empty();
+        int i = 0;
+        for (AbstractItem item : memoryView) {
+            if (item.getName().equals(name)) {
+                return Optional.of(i);
+            }
+            i++;
+        }
+        return Optional.empty();
```
Comment (LucasRyall) [inline source/core/src/main/com/csse3200/game/inventory/Inventory.java:348]: Is there an advantage to using Optional instead of returning -1 for this case, similar to how you've done it in the add method?

**Review by LucasRyall — APPROVED** [review]
Looks good, thanks for fixing this.

File: source/core/src/main/com/csse3200/game/inventory/Inventory.java (hunk 1 above)
Comment (mitsudz) [reply source/core/src/main/com/csse3200/game/inventory/Inventory.java:348]: Nah, both are fine (Optional is probably more readable) - but I don't think it's being used anyway. I had it in in case someone wanted to do something such as checking whether the user has a certain item or number of items on them (e.g. a key to get through to the other area or smthn) but unless that materialises in the next 10 days the code is kind of pointless anyway.

**Review by PHONGNGYUEN1 — COMMENTED** [review]
Much faster no. Not related to the pr but when testing I maxed out inventory and thought we could have an updated dialogue box to tell player has max out their inventory when attempting to pick up another item

**Review by PHONGNGYUEN1 — APPROVED** [review]
